# Generated by Django 5.1.6 on 2025-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='point',
            field=models.IntegerField(),
        ),
    ]
