# Generated by Django 5.1.6 on 2025-02-21 07:35

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_avatar_alter_customer_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.upload_to),
        ),
    ]
