# Generated by Django 5.1.6 on 2025-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('card', 'card'), ('e-wallet', 'e-wallet'), ('cash', 'cash')], default='cash')),
                ('paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
