# Generated by Django 5.1.6 on 2025-03-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_payment_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-id']},
        ),
    ]
