# Generated by Django 5.1.6 on 2025-02-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('IP', 'in_progress'), ('CO', 'completed'), ('CA', 'cancelled')], default='P'),
        ),
    ]
