# Generated by Django 5.1.6 on 2025-02-19 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_oderitem_menu_item_alter_oderitem_order'),
        ('users', '0005_alter_customer_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
    ]
