# Generated by Django 5.1.6 on 2025-02-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_take_away',
            field=models.BooleanField(default=False),
        ),
    ]
