# Generated by Django 5.1.6 on 2025-02-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0007_rename_oderitem_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ManyToManyField(related_name='orders', through='order.OrderItem', to='menu.menuitem'),
        ),
    ]
