# Generated by Django 5.1.6 on 2025-02-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('In progress', 'in_progress'), ('Complete', 'completed'), ('Cancelled', 'cancelled')], default='Pending'),
        ),
    ]
