# Generated by Django 5.1.6 on 2025-02-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_order_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.IntegerField()),
                ('status', models.CharField(choices=[('b', 'out of stock'), ('nb', 'available')], default='nb')),
                ('order', models.ManyToManyField(to='order.order')),
            ],
        ),
    ]
