# Generated by Django 5.1.6 on 2025-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_busy', models.BooleanField(default=False)),
                ('order', models.ManyToManyField(blank=True, null=True, related_name='tables', to='order.order')),
            ],
        ),
    ]
