# Generated by Django 5.1.6 on 2025-03-15 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='order',
        ),
        migrations.AddField(
            model_name='table',
            name='order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
            preserve_default=False,
        ),
    ]
