# Generated by Django 5.1.6 on 2025-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_options_alter_orderitem_order'),
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='location',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='table',
            name='order',
            field=models.ManyToManyField(related_name='table', to='order.order'),
        ),
    ]
