# Generated by Django 5.1.6 on 2025-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_order_options_alter_orderitem_order'),
        ('table', '0002_rename_location_table_number_alter_table_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='table', to='order.order'),
        ),
    ]
