# Generated by Django 5.1.6 on 2025-02-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_alter_table_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='status',
        ),
        migrations.AddField(
            model_name='table',
            name='is_busy',
            field=models.BooleanField(default=False),
        ),
    ]
