# Generated by Django 5.1.6 on 2025-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_create_date_order_number_of_guests_and_more'),
        ('table', '0004_remove_table_status_table_is_busy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, related_name='tables', to='order.order'),
        ),
    ]
